Biblioteca.WebApp/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Biblioteca.WebApp.Helpers;
using Biblioteca.WebApp.Models;
using Biblioteca.WebApp.Models.Books;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;

namespace Biblioteca.WebApp.Controllers
{
    public class BookController : Controller
    {
        private string apiBaseUrl;
        private IConfiguration _Configure;
        private readonly IHttpClientHelper _clientClientHelper;

        public BookController(IConfiguration configuration, IHttpClientHelper clientClientHelper)
        {
            _Configure = configuration;
            _clientClientHelper = clientClientHelper;

            apiBaseUrl = _Configure.GetValue<string>("WebAPIBaseUrl");

        }

        public IActionResult ErrorMessage()
        {
            return Content("Ocorreu algum erro");
        }


        //#region LOCALIZATION
        //private async Task<IActionResult> GetContent(string lang)
        //{
        //    var request = new HttpRequestMessage(HttpMethod.Get, $"{apiBaseUrl}{lang}/Book/GetBookLanguageContent");
        //    var client = _clientFactory.CreateClient();
        //    var response = await client.SendAsync(request);

        //    if (response.StatusCode == System.Net.HttpStatusCode.OK)
        //    {
        //        var responseStream = response.Content.ReadAsStreamAsync();
        //        return Ok(responseStream);
        //    }
        //    else
        //        return ErrorMessage();
        //}
        //#endregion

        #region GET

        // GET COUNTRIES
        private async Task<List<Country>> GetCountries()
        {
            List<Country> countries = new List<Country>();

            // API CALL
            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Country/GetAllCountries";

            var Response = await _clientClientHelper.GetContent(endpoint);
            var result = await Response.Content.ReadAsStringAsync();

            // RESPONSE
            countries = JsonConvert.DeserializeObject<List<Country>>(result);
            return countries;
        }

        // GET AUTHORS
        private async Task<List<Author>> GetAuthors()
        {
            List<Author> authors = new List<Author>();
            // API CALL
            string endpoint = apiBaseUrl + $"{ HttpContext.Session.GetString("language")}/api/Author/GetAllAuthors";
            var Response = await _clientClientHelper.GetContent(endpoint);
            var result = await Response.Content.ReadAsStringAsync();
            // RESPONSE
            authors = JsonConvert.DeserializeObject<List<Author>>(result);
            return authors;
        }

        // GET CATEGORIES
        private async Task<List<Category>> GetCategories()
        {
            List<Category> categories = new List<Category>();

            // API CALL
            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Category/GetAllCategories";
            var Response = await _clientClientHelper.GetContent(endpoint);
            var result = await Response.Content.ReadAsStringAsync();

            // RESPONSE
            categories = JsonConvert.DeserializeObject<List<Category>>(result);
            return categories;
        }

        // GET BOOKS
        private async Task<JsonResult> GetBooks()
        {
            var books = new List<Book>();

            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Book/GetAllByState/{true}";
            // API CALL
            var Response = await _clientClientHelper.GetContent(endpoint);
            var result = await Response.Content.ReadAsStringAsync();
            // RESPONSE
            books = JsonConvert.DeserializeObject<List<Book>>(result);
            return new JsonResult(books);
        }


        // FUNCTION TO CONSTRUCT HTML TABLE
        public async Task<JsonResult> FilterTable(string filter)
        {


            var books = new List<Book>();

            // API CALL
            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Book/GetAllByState/{filter}";
            var Response = await _clientClientHelper.GetContent(endpoint);
            var result = await Response.Content.ReadAsStringAsync();
            books = JsonConvert.DeserializeObject<List<Book>>(result);

            string html = @"<thead>
                        <tr>
                            <th>Id</th>
                            <th>ISBN</th>
                            <th>Titulo</th>
                            <th>País</th>
                            <th>Estado</th>
                        </tr>
                    </thead>
                    <tbody>";

            foreach (var book in books)
            {
                html += @"<tr onclick=location.href='/Book/Update/" + book.Id + "'><td> " + book.Id + " </td><td> " + book.ISBN + " </td><td> " + book.Title + " </td><td> " + book.Country.Name + " </td>";


                html += book.State == true ? "<td> <span class='badge badge-success'>Ativo</span></td>" : "<td><span class='badge badge-danger'>Inativo</span></td>";
                html += "</tr>";
            }

            html += @"</tbody>";

            return new JsonResult(html);
        }

        // GET BOOK BY ID
        private async Task<JsonResult> GetBook(int id)
        {
            Book book = new Book();

            // API CALL
            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Book/GetWithCategoriesAndAuthorById/{id}";

            using (var Response = await _clientClientHelper.GetContent(endpoint))
            {
                var result = await Response.Content.ReadAsStringAsync();
                book = JsonConvert.DeserializeObject<Book>(result);
            }
            return new JsonResult(book);
        }

        // CHECK IF BOOK BY ISBN ALREADY EXISTS
        public async Task<IActionResult> GetBookByISBN(string ISBN)
        {
            List<Book> book = new List<Book>();

            // API CALL
            string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Book/GetBookByISBN/{ISBN}";

            var response = await _clientClientHelper.GetContent(endpoint);
            var result = await response.Content.ReadAsStringAsync();
            book = JsonConvert.DeserializeObject<List<Book>>(result);

            //  IF THE OBJECT BOOK US NULL RETURN FORBIDDEN CODE
            if (book.Count > 0)
                return Json(new { Status = "403" });
            else
                return Json(new { Status = "200" });
        }

        #endregion

        #region Views
        // UPDATE BOOK VIEW
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Book = await GetBook(id);
            HttpContext.Session.SetString("bookId", id.ToString());
            AddViewModel categoriesAuthors = new AddViewModel()
            {
                categories = await GetCategories(),
                authors = await GetAuthors(),
                countries = await GetCountries()
            };
            return View(categoriesAuthors);
        }

        // LIST VIEW
        public async Task<IActionResult> List()
        {
            ViewBag.Books = await GetBooks();
            return View("List");
        }


        // LOAD CATEGORIES,AUTHORS AND COUNTRIES AND GO TO ADD VIEW
        public async Task<IActionResult> Add()
        {
            AddViewModel categoriesAuthors = new AddViewModel()
            {
                categories = await GetCategories(),
                authors = await GetAuthors(),
                countries = await GetCountries()
            };
            return View(categoriesAuthors);
        }

        #endregion

        #region Actions

        // ADD BOOK FUNCTION
        public async Task<IActionResult> AddBook()
        {
            // REQUEST DATA FROM FORM
            var isbn = Request.Form["isbn"];
            var title = Request.Form["title"];
            var categories = Request.Form["categories"];
            var authors = Request.Form["authors"];
            var country = Request.Form["country"];

            if (categories.Count == 0 || authors.Count == 0 || country.Count == 0)
                return ErrorMessage();
            else
            {
                // CREATE BOOK OBJECT
                Book book = new Book();
                book.CountryId = int.Parse(country);
                book.ISBN = int.Parse(isbn);
                book.Title = title;
                book.State = true;

                List<Author> authorsList = new List<Author>();
                List<Category> categoriesList = new List<Category>();

                foreach (var author in authors)
                    authorsList.Add(new Author() { Id = int.Parse(author) });

                foreach (var category in categories)
                    categoriesList.Add(new Category() { Id = int.Parse(category) });


                book.Authors = authorsList;
                book.Categories = categoriesList;

                // API CALL
                HttpContent content = new StringContent(JsonConvert.SerializeObject(book), Encoding.UTF8, "application/json");
                string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Book/CreateBook";
                using (var Response = await _clientClientHelper.PostContent(endpoint, content))
                {
                    if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                        return await List();
                    else
                    {
                        ModelState.Clear();
                        return ErrorMessage();
                    }

Biblioteca.WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Biblioteca.WebApp.Helpers;
using Biblioteca.WebApp.Models.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Biblioteca.WebApp.Controllers
{
    public class UserController : Controller
    {
        private string apiBaseUrl;
        private IConfiguration _Configure;
        private readonly IHttpClientHelper _clientClientHelper;

        public UserController(IConfiguration configuration, IHttpClientHelper clientClientHelper)
        {
            _Configure = configuration;
            _clientClientHelper = clientClientHelper;
            apiBaseUrl = _Configure.GetValue<string>("WebAPIBaseUrl");
        }

        #region GET'S

        private async Task<JsonResult> GetUser(string email)
        {

            var result = await _clientClientHelper.GetContent($"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Client/GetWithCheckoutByEmail/{email}");
            var resutlJson = await result.Content.ReadAsStringAsync();

            Client client = JsonConvert.DeserializeObject<Client>(resutlJson);

            HttpContext.Session.SetString("clientEmail", email);
            HttpContext.Session.SetString("clientId", client.Id.ToString());
            HttpContext.Session.SetString("clientName", client.Name);


            return new JsonResult(client);
        }

        public async Task<string> CheckClient(string email)
        {
            var result = await _clientClientHelper.GetContent($"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Client/GetWithCheckoutByEmail/{email}");
            var resutlJson = await result.Content.ReadAsStringAsync();
            return resutlJson;
        }

        private async Task<JsonResult> GetClients()
        {
            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
            var clients = new List<Client>();

            using (HttpClient client = new HttpClient(httpClientHandler))
            {
                string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Client/GetAllWithCheckout";
                using (var Response = await client.GetAsync(endpoint))
                {
                    var result = await Response.Content.ReadAsStringAsync();
                    clients = JsonConvert.DeserializeObject<List<Client>>(result);
                }

            }
            return new JsonResult(clients);
        }

        #endregion

        #region VIEWS

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult GoToCheckoutAddView()
        {
            return RedirectToRoute(new { Controller = "Checkout", Action = "Add" });
        }

        public IActionResult GoToCheckoutUserView()
        {
            return RedirectToRoute(new { Controller = "Checkout", Action = "CheckoutUser" });
        }

        public async Task<IActionResult> Update(string email)
        {

            var result = await GetUser(email);

            var json = JsonConvert.SerializeObject(result.Value);
            var client = JsonConvert.DeserializeObject<Client>(json);

            ViewBag.User = result;



            HttpContext.Session.SetString("clientId", client.Id.ToString());
            return View();
        }

        public async Task<IActionResult> List()
        {
            ViewBag.Users = await GetClients();
            return View("List");
        }

        #endregion

        public IActionResult ErrorMessage()
        {
            return Content("Ocorreu algum erro");
        }

        #region Actions

        public async Task<IActionResult> AddClient()
        {
            var name = Request.Form["name"];
            var NIF = Request.Form["NIF"];
            var email = Request.Form["email"];

            if (name.Count == 0 || NIF.Count == 0 || email.Count == 0)
                return ErrorMessage();
            else
            {
                var httpClientHandler = new HttpClientHandler();
                httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

                using (HttpClient httpClient = new HttpClient(httpClientHandler))
                {

                    Client client = new Client();
                    client.Email = email;
                    client.NIF = NIF;
                    client.Name = name;
                    client.State = true;
                    client.Registration = DateTime.Now;

                    HttpContent content = new StringContent(JsonConvert.SerializeObject(client), Encoding.UTF8, "application/json");
                    string endpoint = $"{apiBaseUrl}{ HttpContext.Session.GetString("language")}/api/Client/CreateClient";
                    using (var Response = await httpClient.PostAsync(endpoint, content))
                    {
                        if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                        {
                            var result = await Response.Content.ReadAsStringAsync();
                            var clientDatabase = JsonConvert.DeserializeObject<Client>(result);

                            HttpContext.Session.SetString("clientName", name);
                            HttpContext.Session.SetString("clientId", clientDatabase.Id.ToString());
                            return await List();
                        }
                        else
                        {
                            ModelState.Clear();
                            return ErrorMessage();
                        }

                    }
                }
            }
        }

        public async Task<IActionResult> SaveClient()
        {
            var name = Request.Form["name"];
            var NIF = Request.Form["NIF"];
            var state = Request.Form["customSwitch3"];

            if (Request.Form["customSwitch3"].Count > 1)
                state = Request.Form["customSwitch3"][0];

            if (name.Count == 0 || NIF.Count == 0)
                return ErrorMessage();
            else
            {
                var httpClientHandler = new HttpClientHandler();
                httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

                using (HttpClient httpClient = new HttpClient(httpClientHandler))
                {

                    Client client = new Client();
                    client.Email = HttpContext.Session.GetString("clientEmail");
                    client.NIF = NIF;
                    client.Name = name;
                    client.State = bool.Parse(state);

                    HttpContent content = new StringContent(JsonConvert.SerializeObject(client), Encoding.UTF8, "application/json");
                    string endpoint = apiBaseUrl + $"{ HttpContext.Session.GetString("language")}/api/Client/UpdateClient";
                    using (var Response = await httpClient.PostAsync(endpoint, content))
                    {
                        if (Response.StatusCode == System.Net.HttpStatusCode.OK)
                            return await List();
                        else
                        {
                            ModelState.Clear();
                            return ErrorMessage();
                        }

                    }
                }
            }
        }
        #endregion
    }
}

Biblioteca.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Diana - Biblioteca - WebApp</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.css">

    @RenderSection("Styles", false)

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                @*<li class="nav-item">
                    <a class="nav-link white_letters" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>*@
                <li class="nav-item d-none d-sm-inline-block">
                    <a onclick="location.href='@(Url.Action("Index", "Dashboard"))'" class="nav-link white_letters">Dashboard</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link white_letters" data-toggle="dropdown" href="#">
                        <i class="fas fa-globe-europe"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a onclick=GetLanguage('Dashboard','Index','pt-PT') class="dropdown-item">
                            <i class="fas fa-globe-europe mr-2"></i> Português
                        </a>
                        <div class="dropdown-divider"></div>
                        <a onclick=GetLanguage('Dashboard','Index','en-US') class="dropdown-item">
                            <i class="fas fa-globe-europe mr-2"></i> Inglês
                        </a>
                        <div class="dropdown-divider"></div>
                        <a onclick=GetLanguage('Dashboard','Index','es-ES') class="dropdown-item">
                            <i class="fas fa-globe-europe mr-2"></i> Espanhol
                        </a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>

        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a class="brand-link">
                <img src="~/img/istec_logo.png" alt="ISTEC Logo" class="brand-image" style="opacity: .8">
                <span class="brand-text font-weight-light">Biblioteca</span>
            </a>
            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <li class="nav-header">MENU</li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Livros
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview" style="margin-left: 29px;">
                                <li class="nav-item">
                                    <a asp-controller="Book" asp-action="Add" class="nav-link">
                                        <i class="fas fa-plus"></i>
                                        <p>Adicionar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Book" asp-action="List" class="nav-link">
                                        <i class="fas fa-list"></i>
                                        <p>Listar</p>
                                    </a>
                                </li>
                            </ul>

                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>
                                    Clientes
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview" style="margin-left: 29px;">
                                <li class="nav-item">
                                    <a asp-controller="User" asp-action="Add" class="nav-link">
                                        <i class="fas fa-plus"></i>
                                        <p>Adicionar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="User" asp-action="List" class="nav-link">
                                        <i class="fas fa-list"></i>
                                        <p>Listar</p>
                                    </a>
                                </li>
                            </ul>

                        </li>

                        <li class="nav-item">

                            <a asp-controller="Checkout" asp-action="CheckoutListUser" class="nav-link">
                                <i class="nav-icon fas fa-cash-register"></i>
                                <p>
                                    Checkouts
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
            </div>
        </aside>

        <div class="content-wrapper" style="min-height: 859px !important;">
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
        </div>
       
        <footer class="border-top footer text-muted">
            <div class="container" style="margin-left:400px">
                &copy; 2020 - Diana Rodrigues - Biblioteca.WebApp
            </div>
        </footer>
    </div>
 
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>
    

    <!-- LANGUAGE -->
    <script src="~/js/addedJS/language.js"></script>
    <!-- SWEET ALERT -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Biblioteca.WebApp/Views/Shared/_notificationPartial.cshtml
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>

<script>
    var msg = @(TempData["Message"]!=null? Html.Raw(TempData["Message"]) : Html.Raw("undefined"));

    console.log(msg)

    if (msg) {
        if (msg.provider == "sweetAlert") {
            swal.fire({
                title: msg.title,
                text: msg.message,
                icon: msg.icon
            });
        } else {
            toastr[msg.type](msg.message, msg.title);
        }
    }
</script>